### ISSUE TITLE
feature request: add docker installation

### ISSUE THREAD

**Issue by blQSheep** [g3th/IPVanish-Client#1]
Hi could you please add a docker feature incl. GUI web client, docker compose file etc. 
This would be very useful for linux /ubuntu server, raspberry pi & homelab users without GUIs.
Would appreciate. Thanks!

**Comment by g3th** [comment]
Hi there,

For Arch, CentOs, Debian and similar distributions without pre-installed graphic environments a Text-User-Interface could be scripted with little problems, and it should run without being as resource-intensive as Tkinter. This would be highly preferable to running a docker container in my experience.

Since I am currently learning Compose Desktop/Multiplatform, a completely new paradigm for me, I am hoping to port some of these simple interfaces into a more modern framework; therefore, there are no plans to maintain or add features to them, unless something is spectacularly broken.

You are free to fork the project, or simply rewrite it should you wish to do so.

Since this is not on my TODO list, I will close this issue, but you are still free to ask your questions here.
